<a href="https://colab.research.google.com/github/NIlesh-Thamke/Machine-Learning-Practicals/blob/main/Practical2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

#Importing Dataset
input_file = '/content/sales_data_sample.csv'
df = pd.read_csv(input_file, encoding='latin1')
print("Original File")
print(df.head())

Original File
   ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00
1        10121               34      81.35                5  2765.90
2        10134               41      94.74                2  3884.34
3        10145               45      83.26                6  3746.70
4        10159               49     100.00               14  5205.27

         ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0   2/24/2003 0:00  Shipped       1         2     2003  ...
1    5/7/2003 0:00  Shipped       2         5     2003  ...
2    7/1/2003 0:00  Shipped       3         7     2003  ...
3   8/25/2003 0:00  Shipped       3         8     2003  ...
4  10/10/2003 0:00  Shipped       4        10     2003  ...

                    ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0        897 Long Airport Avenue           NaN            NYC    NY
1             59 rue de l'Abbaye           NaN          Reims   NaN
2  27 rue du Colonel Pierre Avia           NaN          Paris   NaN
3             78934 Hillside Dr.           NaN       Pasadena    CA
4                7734 Strong St.           NaN  San Francisco    CA

  POSTALCODE COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE
0      10022     USA       NaN              Yu             Kwai    Small
1      51100  France      EMEA         Henriot             Paul    Small
2      75508  France      EMEA        Da Cunha           Daniel   Medium
3      90003     USA       NaN           Young            Julie   Medium
4        NaN     USA       NaN           Brown            Julie   Medium

[5 rows x 25 columns]

In [8]:
#Deleting Uncessary Column for better understanding
columns_to_drop = ['ADDRESSLINE1', 'ADDRESSLINE2', 'POSTALCODE', 'CITY', 'TERRITORY', 'PHONE']

print("New File after deleting some columns")
print(new_df.head())

New File after deleting some columns
   ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00
1        10121               34      81.35                5  2765.90
2        10134               41      94.74                2  3884.34
3        10145               45      83.26                6  3746.70
4        10159               49     100.00               14  5205.27

         ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  PRODUCTLINE  MSRP  \
0   2/24/2003 0:00  Shipped       1         2     2003  Motorcycles    95
1    5/7/2003 0:00  Shipped       2         5     2003  Motorcycles    95
2    7/1/2003 0:00  Shipped       3         7     2003  Motorcycles    95
3   8/25/2003 0:00  Shipped       3         8     2003  Motorcycles    95
4  10/10/2003 0:00  Shipped       4        10     2003  Motorcycles    95

  PRODUCTCODE              CUSTOMERNAME STATE COUNTRY CONTACTLASTNAME  \
0    S10_1678         Land of Toys Inc.    NY     USA              Yu
1    S10_1678        Reims Collectables   NaN  France         Henriot
2    S10_1678           Lyon Souveniers   NaN  France        Da Cunha
3    S10_1678         Toys4GrownUps.com    CA     USA           Young
4    S10_1678  Corporate Gift Ideas Co.    CA     USA           Brown

  CONTACTFIRSTNAME DEALSIZE
0             Kwai    Small
1             Paul    Small
2           Daniel   Medium
3            Julie   Medium
4            Julie   Medium

In [9]:
#Performing Operation for calculating GST on sales
sales_data_sample = new_df
sales_data_sample['SGST'] = sales_data_sample['SALES'] * 0.09
sales_data_sample['CGST'] = sales_data_sample['SALES'] * 0.09
sales_data_sample['GST'] = sales_data_sample['SGST'] + sales_data_sample['CGST']
print("New File after calculating GST")
print(sales_data_sample.head())

New File after calculating GST
   ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00
1        10121               34      81.35                5  2765.90
2        10134               41      94.74                2  3884.34
3        10145               45      83.26                6  3746.70
4        10159               49     100.00               14  5205.27

         ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  ... PRODUCTCODE  \
0   2/24/2003 0:00  Shipped       1         2     2003  ...    S10_1678
1    5/7/2003 0:00  Shipped       2         5     2003  ...    S10_1678
2    7/1/2003 0:00  Shipped       3         7     2003  ...    S10_1678
3   8/25/2003 0:00  Shipped       3         8     2003  ...    S10_1678
4  10/10/2003 0:00  Shipped       4        10     2003  ...    S10_1678

               CUSTOMERNAME STATE COUNTRY CONTACTLASTNAME CONTACTFIRSTNAME  \
0         Land of Toys Inc.    NY     USA              Yu             Kwai
1        Reims Collectables   NaN  France         Henriot             Paul
2           Lyon Souveniers   NaN  France        Da Cunha           Daniel
3         Toys4GrownUps.com    CA     USA           Young            Julie
4  Corporate Gift Ideas Co.    CA     USA           Brown            Julie

  DEALSIZE      SGST      CGST       GST
0    Small  258.3900  258.3900  516.7800
1    Small  248.9310  248.9310  497.8620
2   Medium  349.5906  349.5906  699.1812
3   Medium  337.2030  337.2030  674.4060
4   Medium  468.4743  468.4743  936.9486

[5 rows x 22 columns]

In [10]:
#Exporting data to new File
print("Updated file store in {sales_data_sample_final}")
final_file = '/content/sales_data_sample_final.csv'
sales_data_sample.to_csv(final_file, index = False)
sales_data_sample.head()

Updated file store in {sales_data_sample_final}

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PRODUCTCODE,CUSTOMERNAME,STATE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,SGST,CGST,GST
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,S10_1678,Land of Toys Inc.,NY,USA,Yu,Kwai,Small,258.3900,258.3900,516.7800
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,S10_1678,Reims Collectables,NaN,France,Henriot,Paul,Small,248.9310,248.9310,497.8620
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,S10_1678,Lyon Souveniers,NaN,France,Da Cunha,Daniel,Medium,349.5906,349.5906,699.1812
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,S10_1678,Toys4GrownUps.com,CA,USA,Young,Julie,Medium,337.2030,337.2030,674.4060
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,S10_1678,Corporate Gift Ideas Co.,CA,USA,Brown,Julie,Medium,468.4743,468.4743,936.9486